name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
          
      - name: Build
        run: |
          go build -v -o redate.exe cmd/main.go

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} redate.exe --generate-notes --title "Release ${{ github.ref_name }}" --notes "Release of redate version ${{ github.ref_name }}. Please refer to the README.md for usage instructions."
        env:
          GH_TOKEN: ${{ github.token }}
